## 舊作業

In [2]:
import numpy as np

In [3]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

### 題目:上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。

### 1. 有多少學生英文成績比數學成績高?

In [4]:
np.sum(np.greater(english_score, math_score))

3

### 2.是否全班同學最高分都是國文?

In [5]:
np.all(np.logical_and(chinese_score > english_score, chinese_score > math_score))

True

## 新作業

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [7]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
print(a + a)
print("----------")
print(a + b)
print("----------")
print(a + c)
print("----------")
print(a + d)
print("----------")
print(a + e)

[ 40  60  80 100]
----------
[21 32 43 54]
----------
[21 31 41 51]
----------
[21 31 41 51]
----------


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

In [ ]:
# 記得先 Import 正確的套件

import numpy as np


In [8]:
A = np.ones(3)*1
B = np.ones(3)*2

print((A+B)*(-A/2))

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [16]:
A = np.ones((1,6))
B = np.ones((6,1))

print(np.dot(A,B)) # A @ B 也會得到相同結果
print(np.outer(A,B)) # A * B 也會得到相同結果

[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
